apiVersion: preql/1.0.0
kind: Database
metadata:
  name: boofy
spec:
  name: boofy
---
apiVersion: preql/1.0.0
kind: Struct
metadata:
  name: people
spec:
  name: person
  databaseName: boofy
---
apiVersion: preql/1.0.0
kind: Struct
metadata:
  name: pet
  labels:
    schema: dbo
    table: pets
    entity: pet
  annotations:
    comment: "A big ol dang table of pets"
spec:
  name: pet
  databaseName: boofy
---
apiVersion: preql/1.0.0
kind: Attribute
metadata:
  name: ownerFirstName
  annotations:
    comment: "Should not be abbreviated"
spec:
  name: ownerFirstName
  structName: pet
  databaseName: boofy
  type: varchar64
  nullable: False
  default: Bob
---
apiVersion: preql/1.0.0
kind: Attribute
metadata:
  name: ownerLastName
  annotations:
    comment: "Should not be abbreviated"
spec:
  name: ownerLastName
  structName: pet
  databaseName: boofy
  type: varchar64
  nullable: False
  default: Bob
  objectIdentifier: '1.38.255.4.6.3'
---
apiVersion: preql/1.0.0
kind: Attribute
metadata:
  name: firstName
  annotations:
    comment: "Should not be abbreviated"
spec:
  name: firstName
  structName: person
  databaseName: boofy
  type: varchar64
  nullable: False
  default: Bob
---
apiVersion: preql/1.0.0
kind: Attribute
metadata:
  name: lastName
  annotations:
    comment: "Should not be abbreviated"
spec:
  name: lastName
  structName: person
  databaseName: boofy
  type: varchar64
  nullable: False
  default: McGobb
---
apiVersion: preql/1.0.0
kind: ForeignKey
metadata:
  name: owner
spec:
  name: owner
  databaseName: boofy
  parentStructName: person
  childStructName: pet
  nullable: False
---
apiVersion: preql/1.0.0
kind: Entry
metadata:
  name: myself
  labels:
    name: boi
spec:
  databaseName: boofy
  structName: person
  id: 1
  distinguishedName: 'lastName=Wilbur,dc=wilbur,dc=space'
  values:
    firstName: Jonathan
    lastName: Wilbur
---
apiVersion: preql/1.0.0
kind: Preamble
metadata:
  name: yeet
spec:
  uncommentedText: 'Dang it bobby'
